# Python Kompaktanleitung

Diese Einleitung in Python basiert auf dem [Python Tutorial](https://github.com/cs231n/cs231n.github.io/blob/master/python-colab.ipynb) von Kevin Zakka.

Diese übersetzte und stellenweise angepasste und gekürzte Fassung wurde von Florian Bohlken und Jan Albrecht im Rahmen der Veranstaltung "Autonome Systeme und mobile Roboter" im Sommersemester 2024 von Prof. Malte Schilling verfasst.

## Einführung

Python ist an sich bereits eine großartige universelle Programmiersprache, aber mit Hilfe einiger beliebter Bibliotheken (numpy, scipy, matplotlib) wird sie zu einer leistungsstarken Umgebung für wissenschaftliches Rechnen.

Wir gehen davon aus, dass viele von euch bereits Erfahrung mit Python und numpy haben. Für diejenigen, die es nicht haben, wird dieser Abschnitt als eine kurze Einführung sowohl in die Python-Programmiersprache als auch in die Verwendung von Python für wissenschaftliches Rechnen dienen.

Folgende Themen werden in dieser Anleitung behandelt:

* **Python Basics**: Grundlegende Datentypen (Container, Listen, Dictionaries, Sets, Tupel), Funktionen, Klassen
* **Numpy**: Arrays, Array-Indizierung, Datentypen, Array-Mathematik, Broadcasting
* **Matplotlib**: Visualisierung, Subplots, Bilder

## Eine kurze Anmerkung zu Python-Versionen

Seit dem 1. Januar 2020 hat Python [offiziell](https://www.python.org/doc/sunset-python-2/) die Unterstützung für `python2` eingestellt. Jupyterhub läuft momentan mit python 3.10, aber auf deinem eigenen Rechner werden die hier gezeigten Funktionen auch mit anderen Versionen kompatibel sein. Als Richtwert sollte diese mindestens Python 3.7 sein. Du kannst deine Python-Version auf der Befehlszeile überprüfen, indem du `python3 --version` ausführst.

In [ ]:
!python3 --version

## Python Basics

Python ist eine dynamisch typisierte high-level Multiparadigma-Programmiersprache. Python-Code wird oft nachgesagt nahezu wie Pseudocode zu sein, da man sehr leistungsstarke Ideen in sehr wenigen Codezeilen sehr lesbar auszudrücken kann. Als Beispiel hier eine Python-Implementierung des klassischen Quicksort-Algorithmus:

In [ ]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)


print(quicksort([3, 6, 8, 10, 1, 2, 1]))

### Grundlegende Datentypen

#### Zahlen

Ganzzahlen (Integers) und Gleitkommazahlen (Floats) funktionieren wie man es von anderen Sprachen erwarten würde:

In [ ]:
x = 3
print(x, type(x))

In [ ]:
print(x + 1)  # Addition
print(x - 1)  # Subtraktion
print(x * 2)  # Multiplikation
print(x**2)  # Exponentiation

In [ ]:
x += 1
print(x)
x *= 2
print(x)

In [ ]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y**2)

Beachte, dass Python im Gegensatz zu vielen anderen Sprachen keine unäre Inkrementations- (`x++`) oder Dekrementations- (`x--`) Operatoren hat. Stattdessen wird dies hier händisch ausgeführt: `x = x + 1`

Python hat auch eingebaute Typen für lange Ganzzahlen und komplexe Zahlen. Du findest alle Details in der [Dokumentation](https://docs.python.org/3.10/library/stdtypes.html#numeric-types-int-float-long-complex).

#### Booleans

Python implementiert alle üblichen Operatoren für Boolesche Logik, verwendet jedoch englische Wörter anstelle von Symbolen (`&&`, `||` usw.):

In [ ]:
t, f = True, False
print(type(t))

Betrachten wir folgend die Operatoren:

In [ ]:
print(t and f)  # Logisches UND;
print(t or f)  # Logisches ODER;
print(not t)  # Logisches NICHT;
print(t != f)  # Logisches XOR;

#### Strings

In [ ]:
hello = "hello"  # Zeichenkettenliterale können einfache Anführungszeichen verwenden
world = "world"  # oder doppelte Anführungszeichen; es spielt keine Rolle
print(hello, len(hello))

In [ ]:
hw = hello + " " + world  # String Konkatenation
print(hw)

In [ ]:
hw12 = "{} {} {}".format(hello, world, 12)  # String Formatierung / Einsetzung
print(hw12)

String-Objekte verfügen über eine Vielzahl nützlicher Methoden - zum Beispiel:

In [ ]:
s = "hello"
print(s.capitalize())  # Ein String wird großgeschrieben; gibt "Hello" aus
print(s.upper())  # Ein String wird in Großbuchstaben umgewandelt; gibt "HELLO" aus
print(
    s.rjust(7)
)  # Ein String wird rechtsbündig ausgerichtet, mit Leerzeichen aufgefüllt
print(s.center(7))  # Ein String wird zentriert, mit Leerzeichen aufgefüllt
print(
    s.replace("l", "(ell)")
)  # Ersetzt alle Vorkommen eines Teilstrings durch einen anderen
print("  world ".strip())  # Entfernt führende und abschließende Leerzeichen

Du kannst eine Liste aller String-Methoden in der [Dokumentation](https://docs.python.org/3.10/library/stdtypes.html#string-methods) finden.

### Container

Python enthält mehrere integrierte Container-Typen: Listen, Wörterbücher, Mengen und Tupel.

#### Listen

Eine Liste entspricht in Python einem Array, ist jedoch in der Größe veränderbar und kann Elemente unterschiedlicher Typen enthalten:

In [ ]:
xs = [3, 1, 2]  # Erstellen einer Liste
print(xs, xs[2])
print(xs[-1])  # Negative Indizes zählen vom Ende der Liste aus; gibt "2" aus

In [ ]:
xs[2] = "foo"  # Listen können Elemente unterschiedlicher Datentypen enthalten
print(xs)

In [ ]:
xs.append("bar")  # Ein neues Element am Ende der Liste hinzufügen
print(xs)

In [ ]:
x = xs.pop()  # Das letzte Element der Liste entfernen und zurückgeben
print(x, xs)

Wie bereits gewohnt findest du alle Details zu Listen in der [Dokumentation](https://docs.python.org/3.10/tutorial/datastructures.html#more-on-lists).

#### Slicing

Zusätzlich zur Möglichkeit einzeln auf Listenlemente zuzugreifen bietet Python eine prägnante Syntax zum Zugriff auf Teillisten - das Slicing:

In [ ]:
nums = list(
    range(5)
)  # range ist eine integrierte Funktion, die eine Liste von ganzen Zahlen erstellt
print(nums)  # Gibt "[0, 1, 2, 3, 4]" aus
print(
    nums[2:4]
)  # Holt einen Ausschnitt von Index 2 bis 4 (exklusiv); gibt "[2, 3]" aus
print(nums[2:])  # Holt einen Ausschnitt von Index 2 bis zum Ende; gibt "[2, 3, 4]" aus
print(
    nums[:2]
)  # Holt einen Ausschnitt vom Anfang bis zum Index 2 (exklusiv); gibt "[0, 1]" aus
print(nums[:])  # Holt einen Ausschnitt der gesamten Liste; gibt "[0, 1, 2, 3, 4]" aus
print(
    nums[:-1]
)  # Indexierung für Ausschnitte kann auch negativ sein; gibt "[0, 1, 2, 3]" aus
nums[2:4] = [8, 9]  # Weist einen neuen Teilliste einem Ausschnitt zu
print(nums)  # Gibt "[0, 1, 8, 9, 4]" aus

#### Schleifen

Man kann folgendermaßen durch die Elemente einer Liste iterieren:

In [ ]:
animals = ["Katze", "Hund", "Affe"]
for animal in animals:
    print(animal)

Wenn du innerhalb einer Schleife auf den Index jedes Elements zugreifen möchtest, verwende die integrierte Funktion `enumerate`:

In [ ]:
animals = ["Katze", "Hund", "Affe"]
for idx, animal in enumerate(animals):
    print("#{}: {}".format(idx + 1, animal))

#### List Comprehensions (Listen Abstraktionen)

Beim Programmieren möchten wir oft einen Datentyp in einen anderen transformieren. Als einfaches Beispiel betrachte den folgenden Code, welcher Quadratzahlen berechnet:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x**2)
print(squares)

Du kannst diesen Code mit einer List Comprehension vereinfachen:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x**2 for x in nums]
print(squares)

_List Comprehensions_ können auch Bedingungen enthalten:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x**2 for x in nums if x % 2 == 0]
print(even_squares)

#### Wörterbücher

Ein Wörterbuch (_dictionary_) speichert (Schlüssel, Wert)-Paare (_key_, _value_), ähnlich wie eine `Map` in Java oder ein Objekt in JavaScript. Du kannst es wie folgt verwenden:

In [ ]:
d = {
    "Katze": "süß",
    "Hund": "haarig",
}  # Erstelle ein neues Wörterbuch mit einigen Daten
print(d["Katze"])  # Holen eines Eintrags aus einem Wörterbuch; gibt "süß" aus
print(
    "Katze" in d
)  # Überprüfen, ob ein Wörterbuch einen bestimmten Schlüssel hat; gibt "True" aus

In [ ]:
d["Fisch"] = "nass"  # Eintrag in einem Wörterbuch setzen
print(d["Fisch"])  # Gibt "nass" aus

In [ ]:
print(d["Affe"])  # KeyError: 'Affe' ist kein Schlüssel in d

In [ ]:
print(
    d.get("Affe", "N/A")
)  # Ein Element mit einem Standardwert abrufen; gibt "N/A" aus
print(
    d.get("Fisch", "N/A")
)  # Ein Element mit einem Standardwert abrufen; gibt "nass" aus

In [ ]:
del d["Fisch"]  # Ein Element aus einem Wörterbuch entfernen
print(d.get("Fisch", "N/A"))  # "Fisch" ist kein Schlüssel mehr; gibt "N/A" aus

Du kannst alles, was du über Wörterbücher wissen musst, in der [Dokumentation](https://docs.python.org/3.10/library/stdtypes.html#dict) finden.

Es ist einfach, über die Schlüssel in einem Wörterbuch zu iterieren:

In [ ]:
d = {"Person": 2, "Katze": 4, "Spinne": 8}
for animal, legs in d.items():
    print("Eine {} hat {} Beine".format(animal, legs))

Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

_Dictionary comprehensions_: Diese sind ähnlich wie _list comprehensions_, ermöglichen es aber eine einfache Konstruktion von Wörterbüchern. Zum Beispiel:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x**2 for x in nums if x % 2 == 0}
print(even_num_to_square)

#### Sets (Mengen)

Ein _set_ ist eine ungeordnete Sammlung von unterschiedlichen Elementen. Als einfaches Beispiel betrachte:

In [ ]:
animals = {"Katze", "Hund"}
print(
    "Katze" in animals
)  # Überprüfe, ob ein Element in einer Menge enthalten ist; gibt "True" aus
print("Fisch" in animals)  # gibt "False" aus

In [ ]:
animals.add("Fisch")  # Füge ein Element zu einer Menge hinzu
print("Fisch" in animals)
print(len(animals))  # Anzahl der Elemente in einer Menge

In [ ]:
animals.add(
    "Katze"
)  # Das Hinzufügen eines Elements, das bereits in der Menge enthalten ist, bewirkt nichts
print(len(animals))
animals.remove("Katze")  # Entferne ein Element aus einer Menge
print(len(animals))

_Loops_: Das Durchlaufen einer Menge hat dieselbe Syntax wie das Durchlaufen einer Liste. Da Mengen jedoch ungeordnet sind, können keine Annahmen darüber getroffen werden, in welcher Reihenfolge die Elemente der Menge besucht werden:

In [ ]:
animals = {"Katze", "Hund", "Fisch"}
for idx, animal in enumerate(animals):
    print("#{}: {}".format(idx + 1, animal))

_Set comprehensions_ (Mengenabstraktionen): Wie bei Listen und Wörterbüchern können wir leicht Mengen mithilfe von _set comprehensions_ erstellen:

In [ ]:
from math import sqrt

print({int(sqrt(x)) for x in range(30)})

#### Tupel

Ein Tupel ist eine (unveränderliche) geordnete Liste von Werten. Ein Tupel ähnelt in vielerlei Hinsicht einer Liste. Einer der wichtigsten Unterschiede besteht darin, dass Tupel als Schlüssel in Wörterbüchern und als Elemente von Mengen verwendet werden können, während das mit Listen nicht möglich ist. Hier ist ein triviales Beispiel:

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Erstelle ein Wörterbuch mit Tupelschlüsseln
t = (5, 6)  # Erstelle ein Tupel
print(type(t))
print(d[t])
print(d[(1, 2)])

In [ ]:
t[0] = 1

### Funktionen

Python-Funktionen werden mit dem `def`-Schlüsselwort definiert. Zum Beispiel:

In [ ]:
def sign(x):
    if x > 0:
        return "positiv"
    elif x < 0:
        return "negativ"
    else:
        return "Null"


for x in [-1, 0, 1]:
    print(sign(x))

Funktionen mit optinalen Parametern definiert man wie folgend gezeigt:

In [ ]:
def hello(name, loud=False):
    if loud:
        print("HALLO, {}".format(name.upper()))
    else:
        print("Hallo, {}!".format(name))


hello("Bob")
hello("Fred", loud=True)

### Klassen

Die Syntax zum Definieren von Klassen in Python ist sehr direkt:

In [ ]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print("HALLO, {}".format(self.name.upper()))
        else:
            print("Hallo, {}!".format(self.name))


g = Greeter("Fred")  # Construct an instance of the Greeter class
g.greet()  # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)  # Call an instance method; prints "HELLO, FRED!"

## Numpy

NumPy ist die Kernbibliothek für wissenschaftliches Rechnen in Python. Sie stellt ein leistungsstarkes multidimensionales Array-Objekt sowie Werkzeuge zum Arbeiten mit diesen Arrays bereit. Da die numpy Bibliotheken in C erstellt wurden sind diese **um ein vielfaches effizienter** als die internen mathematischen Operatoren von python. Dies stellt sich für uns vor allem deswegen als Vorteil heraus, da viele Robotersysteme auch auf leistungsschwächeren integrierten Systemen performant funktionieren müssen.

Um NumPy zu verwenden, müssen wir zunächst das `numpy`-Paket importieren:

In [ ]:
import numpy as np

### Arrays

Ein NumPy-Array ist ein Feld von Werten, die im Gegensatz zu nativem python alle denselben Typ haben und von einem Tupel nicht-negativer Ganzzahlen indiziert werden. Die Anzahl der Dimensionen entspricht dem Rang des Arrays. Die `shape` (Form) eines Arrays ist ein Tupel von ganzen Zahlen, das die Größe der Dimensionen angibt.

Wir können NumPy-Arrays aus verschachtelten Python-Listen initialisieren und auf Elemente mit eckigen Klammern zugreifen:

In [ ]:
a = np.array([1, 2, 3])  # Erstelle ein Array vom Rang 1
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5  # Ändere ein Element des Arrays
print(a)

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])  # Erstelle ein Array vom Rang 2
print(b)

In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

NumPy bietet auch viele Funktionen zum Erstellen von Arrays:

In [ ]:
a = np.zeros((2, 2))  # Erstelle ein Array aus Nullen
print(a)

In [ ]:
b = np.ones((1, 2))  # Erstelle ein Array aus Einsen
print(b)

In [ ]:
c = np.full((2, 2), 7)  # Erstelle ein konstantes Array
print(c)

In [ ]:
d = np.eye(2)  # Erstelle eine 2x2 Identitäts-Matrix
print(d)

In [ ]:
e = np.random.random(
    (2, 2)
)  # Erstelle ein Array, welches mit zufälligen Werten gefüllt ist
print(e)

### Array Indexierung

NumPy bietet verschiedene Möglichkeiten, auf Arrays zuzugreifen.

_Slicing_: Ähnlich wie Python-Listen können auch Numpy-Arrays gesliced werden. Da Arrays mehrdimensional sein können, musst du für jede Dimension des Arrays einen Bereich angeben:

In [ ]:
import numpy as np

# Erstelle das folgende Array mit Rang 2 mit der Form (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Verwende Slicing, um das Teilarray bestehend aus den ersten 2 Zeilen
# und den Spalten 1 und 2 zu extrahieren; b ist das folgende Array mit der Form (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

Ein Ausschnitt (_slice_) eines Arrays ist eine Ansicht der Original-Daten. Das heißt, dass jede Modifikation des Ausschnitts auch das ursprüngliche Array ändern wird.

In [ ]:
print(a[0, 1])
b[0, 0] = 77  # b[0, 0] sind die gleichen Daten wie a[0, 1]
print(a[0, 1])

Du kannst auch Ganzzahl-Indexierung mit Slice-Indexierung mischen. Dies führt jedoch zu einem Array mit niedrigerem Rang als das Originalarray:

In [ ]:
# Erstelle das folgende Array vom Rang 2 mit der Form (3, 4)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

Somit ergeben sich zwei Möglichkeiten, auf die Daten in der mittleren Zeile des Arrays zuzugreifen.
Einerseits die Kombination von Ganzzahl-Indexierung mit Slices - diese ergibt ein Array mit niedrigerem Rang,
andererseits die ausschließliche Verwendung von Slices - was dann ein Array mit demselben Rang wie das ursprüngliche Array ergibt:

In [ ]:
row_r1 = a[1, :]  # Rang 1 Ansicht der zweiten Reihe von a
row_r2 = a[1:2, :]  # Rang 2 Ansicht der zweiten Reihe von a
row_r3 = a[[1], :]  # Rang 2 Ansicht der zweiten Reihe von a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

In [ ]:
# Wir können beim Zugriff auf die Spalten die gleiche Unterscheidung betrachten:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

**Ganzzahl-Array-Indexierung**: Wenn du in NumPy-Arrays mit Slicing indizierst, wird die resultierende Array-Ansicht immer ein Teilarray des ursprünglichen Arrays sein. Im Gegensatz dazu ermöglicht dir die Ganzzahl-Array-Indexierung, beliebige Arrays unter Verwendung der Daten aus einem anderen Array zu konstruieren. Hier ist ein Beispiel:

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])

# Ein Beispiel der Ganzzahl-Array-Indexierung.
# Das zurückgegebene Array hat dann die Form (3,)
print(a[[0, 1, 2], [0, 1, 0]])

# Das folgende Beispiel der Ganzzahl-Array-Indexierung ist also äquivalent zur obigen:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
# Bei der Verwendung von Ganzzahl-Array-Indexierung kannst du dasselbe
# Element aus dem Quellarray wiederverwenden:
print(a[[0, 0], [1, 1]])

# Äquivalent zum vorherigen Beispiel für Ganzzahl-Array-Indexierung
print(np.array([a[0, 1], a[0, 1]]))

Ein nützlicher Trick bei der Ganzzahl-Array-Indexierung besteht darin, ein Element aus jeder Zeile einer Matrix auszuwählen oder zu ändern:

In [ ]:
# Erstellen wir dazu ein neues Array aus dem wir Elemente auswählen
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

In [ ]:
# Erstelle ein Array an Indizes
b = np.array([0, 2, 0, 1])

# Wähle ein Element aus jeder Zeile von a unter Verwendung der Indizes in b aus
print(a[np.arange(4), b])  # Gibt "[ 1  6  7 11]" aus

In [ ]:
# Ändere ein Element aus jeder Zeile von a unter Verwendung der Indizes in b
a[np.arange(4), b] += 10
print(a)

Boolesche Array-Indexierung: Mit der booleschen Array-Indexierung kannst du beliebige Elemente eines Arrays auswählen. Häufig wird diese Art der Indexierung verwendet, um die Elemente eines Arrays auszuwählen, die eine bestimmte Bedingung erfüllen. Hier ist ein Beispiel:

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = a > 2  # Finde die Elemente von a, die größer als 2 sind;
# dies gibt ein numpy-Array aus Booleans mit derselben
# Form wie a zurück, wobei jeder Platz von bool_idx angibt,
# ob das entsprechende Element von a > 2 ist.

print(bool_idx)

In [ ]:
# Wir verwenden die boolesche Array-Indexierung, um ein Array vom Rang 1 zu konstruieren,
# das aus den Elementen von a besteht, die den True-Werten von bool_idx entsprechen
print(a[bool_idx])

# Du kannst auch alles zusammen direkt in einer einzigen kompakten Anweisung tun:
print(a[a > 2])

Um nicht zu sehr auszuschweifen, werden hier viele Details zur Indexierung von NumPy-Arrays ausgelassen. Wenn du mehr erfahren möchtest, kannst du auch hier die [Dokumentation](https://numpy.org/doc/stable/reference/generated/numpy.array.html) lesen.

### Datentypen

Jedes NumPy-Array ist ein Raster von Elementen desselben Typs. NumPy bietet eine große Auswahl an numerischen Datentypen, die du zum Konstruieren von Arrays verwenden kannst. NumPy versucht, einen Datentyp zu erraten, wenn du ein Array erstellst - Funktionen, die Arrays konstruieren, enthalten aber normalerweise auch einen optionalen Parameter, um den Datentypen explizit anzugeben. Hier ist ein Beispiel:

In [ ]:
x = np.array([1, 2])  # Lasse NumPy den Datentyp wählen
y = np.array([1.0, 2.0])  # Lasse NumPy den Datentyp wählen
z = np.array([1, 2], dtype=np.int64)  # Erzwinge einen bestimmten Datentyp

print(x.dtype, y.dtype, z.dtype)

Alles weitere über NumPy Datentypen kannst du in der [Dokumentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html) lesen.

### Array Mathematik

Grundlegende mathematische Funktionen arbeiten elementweise auf Arrays und sind sowohl als Operatorüberladungen als auch als Funktionen im NumPy-Modul verfügbar:

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Elementweise Summe; beide Varianten erzeugen das Array
# [[ 6.  8.]
#  [10. 12.]]
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementweise Differenz; beide Varianten erzeugen das Array
# [[-4. -4.]
#  [-4. -4.]]
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementweise Produkt; beide Varianten erzeugen das Array
# [[ 5. 12.]
#  [21. 32.]]
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementweise Division; beide Varianten erzeugen das Array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementweise Quadratwurzel; erzeugt das Array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Beachte hierbei, dass `*` eine elementweise Multiplikation und keine Matrixmultiplikation ist. Wir verwenden stattdessen die `dot`-Funktion, um das innere Produkt von Vektoren zu berechnen, einen Vektor mit einer Matrix zu multiplizieren und um Matrizen zu multiplizieren. `dot` ist sowohl als Funktion im NumPy-Modul als auch als Instanzmethode von Array-Objekten verfügbar:

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Inneres Produkt von Vektoren; beides produziert 219
print(v.dot(w))
print(np.dot(v, w))

Du kannst dafür auch den `@` Operator nutzen, welcher äquivalent zu NumPy's `dot` Operator ist.

In [ ]:
print(v @ w)

In [ ]:
# Produkt von Matrix und Vektor; alle Varianten produzieren das Array [29 67] vom Rang 1
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Produkt zweier Matrizen; alle Varianten produzieren folgendes Array vom Rang 2:
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

NumPy bietet viele nützliche Funktionen an, um Berechnungen auf Arrays durchzuführen; eine der nützlichsten ist `sum`:

In [ ]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))  # Berechne die Summe aller Elemente; gibt "10" aus
print(np.sum(x, axis=0))  # Berechne die Summe jeder Spalte; gibt "[4 6]" aus
print(np.sum(x, axis=1))  # Berechne die Summe jeder Zeile; gibt "[3 7]" aus

Du kannst die vollständige Liste der mathematischen Funktionen von NumPy in der [Dokumentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html) finden.

Neben der Berechnung mathematischer Funktionen mit Arrays müssen wir häufig Daten in Arrays umformen oder anderweitig manipulieren. Das einfachste Beispiel dafür ist die Transposition einer Matrix; um eine Matrix zu transponieren, verwende einfach das Attribut `T` eines Array-Objekts:

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1, 2, 3]])
print(v)
print("transpose\n", v.T)

### Broadcasting

Broadcasting ist ein leistungsstarker Mechanismus, der es NumPy ermöglicht bei der Durchführung arithmetischer Operationen mit Arrays unterschiedlicher Formen zu arbeiten. Oft haben wir ein kleineres und ein größeres Array und möchten das kleinere Array mehrmals verwenden, um eine Operation auf dem größeren Array durchzuführen.

Nehmen wir zum Beispiel an, dass wir einen konstanten Vektor zu jeder Zeile einer Matrix addieren möchten, können wir das so machen:

In [ ]:
# Wir werden den Vektor v zu jeder Zeile der Matrix x hinzufügen
# und das Ergebnis in der Matrix y speichern
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)  # Erzeuge eine leere Matrix mit der gleichen Form wie x

# Füge den Vektor v zu jeder Zeile der Matrix x mit einer expliziten Schleife hinzu
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

Das funktioniert zwar, jedoch kann eine explizite Schleife in Python sehr langsam sein, wenn die Matrix `x` sehr groß ist. Übrigens ist das Hinzufügen des Vektors `v` zu jeder Zeile der Matrix `x` äquivalent dazu, eine Matrix `vv` zu bilden, indem mehrere Kopien von `v` vertikal gestapelt werden, und dann die elementweise Summation von `x` und `vv` durchzuführen. Wir könnten diesen Ansatz folgendermaßen implementieren:

In [ ]:
vv = np.tile(v, (4, 1))  # Staple 4 Kopien von v übereinander
print(vv)  # Gibt "[[1 0 1]
#        [1 0 1]
#        [1 0 1]
#        [1 0 1]]" aus

In [ ]:
y = x + vv  # Addiere x und vv elementweise
print(y)

NumPy-Broadcasting ermöglicht es uns, diese Berechnung durchzuführen, ohne tatsächlich mehrere Kopien von `v` zu erstellen. Betrachte diese Version, die Broadcasting verwendet:

In [ ]:
import numpy as np

# Wir werden den Vektor v zu jeder Zeile der Matrix x hinzufügen,
# und das Ergebnis in der Matrix y speichern
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Addiere v per Broadcasting zu jeder Zeile von x
print(y)

Durch das Broadcasting funktioniert die Zeile `y = x + v`, obwohl `x` die Form `(4, 3)` und `v` die Form `(3,)` hat. Diese Zeile funktioniert so, als ob `v` tatsächlich die Form `(4, 3)` hätte - wobei jede Zeile eine Kopie von `v` wäre und die Summe elementweise durchgeführt würde.

Zwei Arrays 'zusammenzubroadcasten' folgt diesen Regeln:

1. Wenn die Arrays nicht denselben Rang haben, stellen sie der Form des Arrays mit dem niedrigeren Rang Einsen vorne an, bis beide Formen dieselbe Länge haben.
2. Die beiden Arrays sind in einer Dimension kompatibel, wenn diese bei beiden gleich groß oder bei einem der Arrays Eins ist.
3. Ein Broadcast ist möglich, wenn die Arrays in allen Dimensionen kompatibel sind.
4. Nach dem Broadcasting verhält sich jedes Array, als ob es die Form des elementweisen Maximums der Formen der beiden Eingabearrays hätte.
5. In jeder Dimension, in der ein Array die Größe Eins und das andere Array eine Größe größer als Eins hatte, verhält sich das erste Array, als ob es entlang dieser Dimension kopiert worden wäre.

Wenn diese Erklärung nicht verständlich ist, versuche die Erklärung aus der [Dokumentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) oder diese [Erklärung](http://wiki.scipy.org/EricsBroadcastingDoc) zu lesen.

Funktionen, die Broadcasting unterstützen, werden als universelle Funktionen bezeichnet. Du kannst die Liste aller universellen Funktionen in der [Dokumentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs) finden.

Hier sind einige Anwendungen von Broadcasting:

In [ ]:
# Berechne das äußere Produkt von Vektoren
v = np.array([1, 2, 3])  # v hat die Form (3,)
w = np.array([4, 5])  # w hat die Form (2,)
# Um ein äußeres Produkt zu berechnen, formen wir v zuerst zu einem
# Spaltenvektor der Form (3, 1) um; dann können wir es gegen w broadcasten,
# um eine Ausgabe der Form (3, 2) zu erhalten,
# was das äußere Produkt von v und w ist:

print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Füge einen Vektor zu jeder Zeile einer Matrix hinzu
x = np.array([[1, 2, 3], [4, 5, 6]])
# x hat Form (2, 3) und v hat Form (3,), also broadcasten sie zu (2, 3),
# und ergeben die folgende Matrix:

print(x + v)

In [ ]:
# Füge einen Vektor zu jeder Spalte einer Matrix hinzu
# x hat Form (2, 3) und w hat Form (2,).
# Wenn wir x transponieren, hat es Form (3, 2) und kann gegen w gebroadcastet
# werden, um ein Ergebnis der Form (3, 2) zu erhalten; das Transponieren dieses
# Ergebnisses liefert das endgültige Ergebnis der Form (2, 3), das die Matrix x
# ist, bei welcher der Vektor w zu jeder Spalte hinzugefügt wurde.
# Ergibt die folgende Matrix:

print((x.T + w).T)

In [ ]:
# Eine weitere Lösung besteht darin, w in einen Zeilenvektor der Form (2, 1)
# umzuformen; wir können es dann direkt gegen x broadcasten, um dieselbe
# Ausgabe zu erzeugen.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiplizieren einer Matrix mit einer Konstanten:
# x hat die Form (2, 3). NumPy behandelt Skalare als Arrays der Form ();
# diese können per broadcasting zusammengeführt werden, um die Form (2, 3)
# zu erzeugen, produzieren also das folgende Array:
print(x * 2)

Broadcasting macht deinen Code in der Regel kompakter und schneller, daher solltest du versuchen es wann immer möglich auch anzuwenden.

Diese kurze Übersicht hat viele wichtige Dinge angesprochen, die man über NumPy wissen sollte, ist jedoch bei weitem nicht vollständig. Schaue dir die [NumPy-Referenz](http://docs.scipy.org/doc/numpy/reference/) an, um noch viel mehr über NumPy zu erfahren.

## Matplotlib

Matplotlib ist eine Plotting-Bibliothek. Diesem Abschnitt ist eine kurze Einführung in das Modul `matplotlib.pyplot`, das es ermöglicht Daten grafisch auszugeben, was in vielen Situationen die Auswertung von z.B. Sensordaten ermöglicht und euch damit die Entwicklung erheblich erleichtern kann.

In [ ]:
import matplotlib.pyplot as plt

### Plotting

Die wichtigste Funktion in `matplotlib` ist `plot`, mit der du 2D-Daten plotten kannst. Hier ist ein einfaches Beispiel:

In [ ]:
# Berechne die x- und y-Koordinaten für Punkte auf einer Sinuskurve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plotte die Punkte mit matplotlib
plt.plot(x, y)

Mit nur ein wenig zusätzlicher Arbeit können wir problemlos mehrere Linien gleichzeitig plotten und einen Titel, eine Legende und Achsenbeschriftungen hinzufügen:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plotte die Punkte mit matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel("x-Achsenbeschriftung")
plt.ylabel("y-Achsenbeschriftung")
plt.title("Sinus und Cosinus")
plt.legend(["Sinus", "Cosinus"])

### Subplots 

Du kannst verschiedene Dinge im selben Diagramm mit der Funktion `subplot` plotten. Hier ist ein Beispiel:

In [ ]:
# Berechne die x- und y-Koordinaten für Punkte auf den Sinus- und Kosinus-Kurven.
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Richte ein Subplot-Raster ein, das eine Höhe von 2 und eine Breite von 1 hat,
# und setze das erste solche Subplot als aktiv.
plt.subplot(2, 1, 1)

# Erstelle den ersten Plot.
plt.plot(x, y_sin)
plt.title("Sinus")

# Setze den zweiten Subplot als aktiv und plote zum zweiten mal.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title("Kosinus")

# Zeige das Diagramm an.
plt.show()

Du kannst viel mehr über die `subplot`-Funktion in der [Dokumentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplot.html) nachlesen.